# PARAMETERS
#SERVER_PARAMETERS
server.ipAddress=127.0.0.1
server.port=1234


# height = number of row
# width = number of column
    # board parameter
board.height=9
board.width=9
    # bookshelf parameter
bookshelf.height=6
bookshelf.width=5

# Maximum number of players per game
maxNumberPlayers=4

##### BOARD SECTION #####
board=0,0,0,3,4,0,0,0,0,0,0,0,2,2,4,0,0,0,0,0,3,2,2,2,3,0,0,0,4,2,2,2,2,2,2,3,4,2,2,2,2,2,2,2,4,3,2,2,2,2,2,2,4,0,0,0,3,2,2,2,3,0,0,0,0,0,4,2,2,0,0,0,0,0,0,0,4,3,0,0,0

##### STACK SECTION #####
# Stack depend on how many players are currently playing (at the beginning of the match)
# String rule = "stack"+ num_of_player +"players";  //<---- Java snippet
stack.2players=4,8
stack.2dim=2
stack.3players=4,6,8
stack.3dim=3
stack.4players=2,4,6,8
stack.4dim=4


##### CARDS SECTION #####
# Numbers of different items of the same card
# example:
#       items.diffNumbers=3 means that there will be 3 "CATS" item
items.diffNumbers=3

# Maximum number of card drowable
cards.maxDrowable=3
cards.maxNumberPerType=22

# Common goal card
cards.maxCommonGoal=2

##### SCORE SECTION - personal goals #####
# Score relative to numbers of goals achieved
score.0goal=0
score.1goal=1
score.2goal=2
score.3goal=4
score.4goal=6
score.5goal=9
score.6goal=12
    # minimum number of goals achievable
score.minNum=0
score.maxNum=6

#score for adjacent
score.adj3=2
score.adj4=3
score.adj5=5
score.adj6=8
score.MinlimitParameter=3
score.MaxlimitParameter=6
