package utils;

public enum Event {

    LOGIN ,WAIT_START_OF_MATCH ,LOGIN_TRUE ,LOGIN_FALSE, PLAYER_DRAW_POSITIVE, PLAYER_INSERT_POSITIVE,PLAYER_DRAW_NEGATIVE, PLAYER_INSERT_NEGATIVE, PLAYER_FINISH, NEW_MATCH, NEW_TURN, GAME_INIT, FINISH_MATCH, GET_CHAT, SEND_MESSAGE


}
