package utils;

/**
 * Enumerates all the possible events that can be sent between the server and client.
 */
public enum Event {

    LOGIN ,WAIT_START_OF_MATCH ,LOGIN_TRUE , PLAYER_DRAW_POSITIVE, PLAYER_INSERT_POSITIVE,PLAYER_DRAW_NEGATIVE, PLAYER_INSERT_NEGATIVE, PLAYER_FINISH, NEW_TURN, GAME_INIT, FINISH_MATCH, GET_CHAT, EXIT_CHAT, SEND_MESSAGE, PING,CONNECTION_PROBLEM,RECONNECTION, DELETE_MATCH, FORCED_END_MATCH, NEW_TURN_RECONNECTED, CLIENT_CLOSE


}
