package model;

import model.board.Board;
import model.board.FourBoard;
import model.board.TwoBoard;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class BoardGeneratorTest {

    @Test
    void getBoard() {
            BoardGenerator generator = new BoardGenerator(4);

            boolean valid= generator.getBoard().getBox(0,0).getValid();
            assertTrue(valid==false);
              boolean valido= generator.getBoard().getBox(0,2).getValid();
            assertTrue(valido==false);
            Boolean va= generator.getBoard().getBox(0,4).getValid();
            assertTrue(va==true);
        Boolean vali= generator.getBoard().getBox(0,6).getValid();
            assertTrue(vali==false);
        Boolean val= generator.getBoard().getBox(0,8).getValid();
        assertTrue(val==false);
        Boolean v= generator.getBoard().getBox(1,1).getValid();
        assertTrue(v==false);
        Boolean vaer= generator.getBoard().getBox(1,3).getValid();
        assertTrue(vaer==true);
        Boolean ciao= generator.getBoard().getBox(1,5).getValid();
        assertTrue(ciao==true);
        Boolean cia= generator.getBoard().getBox(1,7).getValid();
        assertTrue(cia==false);
        Boolean cio= generator.getBoard().getBox(2,0).getValid();
        assertTrue(cio==false);
        Boolean moin= generator.getBoard().getBox(2,2).getValid();
        assertTrue(moin==true);
        Boolean min= generator.getBoard().getBox(2,4).getValid();
        assertTrue(min==true);
        Boolean fic= generator.getBoard().getBox(2,6).getValid();
        assertTrue(fic==true);
        Boolean zin= generator.getBoard().getBox(2,8).getValid();
        assertTrue(zin==false);
        Boolean pin= generator.getBoard().getBox(3,1).getValid();
        assertTrue(pin==true);
        Boolean macho= generator.getBoard().getBox(3,3).getValid();
        assertTrue(macho==true);
        Boolean a= generator.getBoard().getBox(3,5).getValid();
        assertTrue(a==true);
        Boolean l= generator.getBoard().getBox(3,7).getValid();
        assertTrue(l==true);
        Boolean d= generator.getBoard().getBox(4,0).getValid();
        assertTrue(d==true);
        Boolean lin= generator.getBoard().getBox(4,2).getValid();
        assertTrue(lin==true);
        Boolean id= generator.getBoard().getBox(4,4).getValid();
        assertTrue(id==true);
        Boolean pr= generator.getBoard().getBox(4,6).getValid();
        assertTrue(pr==true);
        Boolean co= generator.getBoard().getBox(4,8).getValid();
        assertTrue(co==true);
        Boolean cop= generator.getBoard().getBox(5,1).getValid();
        assertTrue(cop==true);
        Boolean piv= generator.getBoard().getBox(5,3).getValid();
        assertTrue(piv==true);
        Boolean crin= generator.getBoard().getBox(5,5).getValid();
        assertTrue(crin==true);
        Boolean fo= generator.getBoard().getBox(5,7).getValid();
        assertTrue(fo==true);
        Boolean cod= generator.getBoard().getBox(6,0).getValid();
        assertTrue(cod==false);
        Boolean crilin= generator.getBoard().getBox(6,2).getValid();
        assertTrue(crilin==true);
        Boolean goku= generator.getBoard().getBox(6,4).getValid();
        assertTrue(goku==true);
        Boolean tu= generator.getBoard().getBox(6,6).getValid();
        assertTrue(tu==true);
        Boolean k= generator.getBoard().getBox(6,8).getValid();
        assertTrue(k==false);
        Boolean y= generator.getBoard().getBox(7,1).getValid();
        assertTrue(y==false);
        Boolean p= generator.getBoard().getBox(7,3).getValid();
        assertTrue(p==true);
        Boolean pon= generator.getBoard().getBox(7,5).getValid();
        assertTrue(pon==true);
        Boolean fokr= generator.getBoard().getBox(7,7).getValid();
        assertTrue(fokr==false);
        Boolean caio= generator.getBoard().getBox(8,0).getValid();
        assertTrue(caio==false);
        Boolean cai= generator.getBoard().getBox(8,2).getValid();
        assertTrue(cai==false);
        Boolean vaop= generator.getBoard().getBox(8,4).getValid();
        assertTrue(vaop==true);
        Boolean ork= generator.getBoard().getBox(8,6).getValid();
        assertTrue(ork==false);
        Boolean fom= generator.getBoard().getBox(8,8).getValid();
        assertTrue(fom==false);

        BoardGenerator generators = new BoardGenerator(2);
        boolean q= generators.getBoard().getBox(0,3).getValid();
        System.out.println(q);
        assertTrue(q==false);
        boolean o= generators.getBoard().getBox(0,4).getValid();
        assertTrue(o==false);
        Boolean vaw= generators.getBoard().getBox(1,5).getValid();
        assertTrue(vaw==false);
        Boolean valipo= generators.getBoard().getBox(2,2).getValid();
        assertTrue(valipo==false);
        Boolean valin= generators.getBoard().getBox(2,6).getValid();
        assertTrue(valin==false);
        Boolean copa= generators.getBoard().getBox(3,1).getValid();
        assertTrue(copa==false);
        Boolean chia= generators.getBoard().getBox(3,8).getValid();
        assertTrue(chia==false);
        Boolean cib= generators.getBoard().getBox(4,0).getValid();
        assertTrue(cib==false);
        Boolean cilia= generators.getBoard().getBox(4,8).getValid();
        assertTrue(cilia==false);
        Boolean will= generators.getBoard().getBox(5,0).getValid();
        assertTrue(will==false);
        Boolean Zika= generators.getBoard().getBox(5,7).getValid();
        assertTrue(Zika==false);
        Boolean Niko= generators.getBoard().getBox(6,2).getValid();
        assertTrue(Niko==false);
        Boolean piy= generators.getBoard().getBox(6,6).getValid();
        assertTrue(piy==false);
        Boolean figaro= generators.getBoard().getBox(7,3).getValid();
        assertTrue(figaro==false);
        Boolean molina= generators.getBoard().getBox(8,4).getValid();
        assertTrue(molina==false);
        Boolean sensuous= generators.getBoard().getBox(8,5).getValid();
        assertTrue(sensuous==false);
    }
}